language: go

go:
  - "1.12"

# Restrict to cloning only 1 commit.
git:
  depth: 1

sudo: false

install:
  - go get github.com/jmoiron/sqlx
  - go get github.com/lib/pq
  - go get github.com/sirupsen/logrus
  - go get github.com/DATA-DOG/go-sqlmock
  - go get gopkg.in/yaml.v2
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v ./database/ ./wflib/ --covermode=count --coverprofile=coverage.out

after_script:
  - goveralls --coverprofile=coverage.out --service=travis-ci --repotoken $COVERALLS_TOKEN
